---
title: Een koptelefoon aansluiten
hero_image: images/banner.png
description: Hoe kan je een koptelefoon aansluiten op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - title: Een koptelefoon aansluiten
