title: Wire earphones
hero_image: images/banner.png
description: How to wire earphones to a Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - 
    title: Wire earphones
