
title: Connecter des écouteurs
hero_image: images/banner.png
description: Comment connecter des écouteurs à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - title: Connecter des écouteurs
